site_name: Shoutrrr
site_url: http://containrrr.github.io/shoutrrr/
repo_url: https://github.com/containrrr/shoutrrr/
theme:
  name: 'material'
  palette:
    primary: cyan
    accent: cyan
  logo: shoutrrr-x180.png
  favicon: favicon.ico
markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
  - codehilite
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  - Services:
    - Overview: 'services/overview.md'
    - Discord: 'services/discord.md'
    - Hangouts Chat: 'services/hangouts.md'
plugins:
  - search
