site_name: Shoutrrr
site_url: https://containrrr.dev/shoutrrr/
repo_url: https://github.com/containrrr/shoutrrr/
edit_uri: edit/main/docs/index.md
theme:
  name: 'material'
  palette:
    scheme: shoutrrr
  logo: shoutrrr-180px.png
  favicon: favicon.ico
extra_css:
  - stylesheets/theme.css
markdown_extensions:
  - toc:
      permalink: True
      separator: '_'
  - codehilite
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  - 'Overview': 'services/overview.md'
  - Services:
      - Discord: 'services/discord.md'
      - Hangouts Chat: 'services/hangouts.md'
      - Pushover: 'services/pushover.md'
      - Teams: 'services/teams.md'
      - Telegram: 'services/telegram.md'
      - Zulip Chat: 'services/zulip.md'
  - Advanced usage:
      - Proxy: 'proxy.md'

plugins:
  - search
