site_name: Shoutrrr
site_url: https://containrrr.dev/shoutrrr/
repo_url: https://github.com/containrrr/shoutrrr/
edit_uri: !!python/object/apply:os.getenv [DOCS_EDIT_URI, '/edit/main/docs/']
theme:
  name: 'material'
  palette:
    scheme: shoutrrr
  logo: shoutrrr-180px.png
  favicon: favicon.ico
  custom_dir: docs/overrides
extra:
  version:
    provider: mike
  generator: false
extra_css:
  - stylesheets/theme.css
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: True
      separator: '_'
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  - 'Service Overview': 'services/overview.md'
  - Services:
      - Bark: 'services/bark.md'
      - Discord: 'services/discord.md'
      - Email: 'services/email.md'
      - Gotify: 'services/gotify.md'
      - Google Chat: 'services/googlechat.md'
      - IFTTT: 'services/ifttt.md'
      - Join: 'services/join.md'
      - Mattermost: 'services/mattermost.md'
      - Matrix: 'services/matrix.md'
      - Ntfy: 'services/ntfy.md'
      - OpsGenie: 'services/opsgenie.md'
      - Pushbullet: 'services/pushbullet.md'
      - Pushover: 'services/pushover.md'
      - Rocketchat: 'services/rocketchat.md'
      - Slack: 'services/slack.md'
      - Teams: 'services/teams.md'
      - Telegram: 'services/telegram.md'
      - Zulip Chat: 'services/zulip.md'
      - Generic Webhook: 'services/generic.md'
  - Guides:
      - Slack: 'guides/slack/index.md'
  - Examples:
      - Generic Webhook: 'examples/generic.md'
  - Advanced usage:
      - Proxy: 'proxy.md'

plugins:
  - search